theme: jekyll-theme-minimal
title: Página principal de ualvar500
description: Guarda la página para mantenerte al tanto de posibles cambios!
user_image: /assets/imágenes/Captura de pantalla 2025-12-04 182125.png
